[build]
  command = "pnpm build"
  publish = "dist"

[[edge_functions]]
  path = "/*"
  function = "protect"

[[redirects]]
  from = "/ghostfees"
  to = "/appendix/fee-calculator/"
  status = 301

[[redirects]]
  from = "/ghostfees/*"
  to = "/appendix/fee-calculator/:splat"
  status = 301

[[redirects]]
  from = "/ghost-fees"
  to = "/appendix/fee-calculator/"
  status = 301

[[redirects]]
  from = "/ghost-fees/*"
  to = "/appendix/fee-calculator/:splat"
  status = 301

[[redirects]]
  from = "/redditizer"
  to = "/appendix/redditizer/"
  status = 301

[[redirects]]
  from = "/redditizer/*"
  to = "/appendix/redditizer/:splat"
  status = 301

[dev]
  command = "pnpm dev"
  targetPort = 5173
